name: peridot
description: "Nostr bunker for desktop."
publish_to: 'none'
version: 0.5.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_highlight: ^0.7.0
  flutter_local_notifications: ^19.4.2
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  get: ^4.7.2
  google_fonts: ^6.3.2
  intl: any
  launch_at_startup: ^0.5.1
  ndk: ^0.6.0-dev.8
  nip01: ^0.3.0+1
  nip19: ^0.2.0
  nip49: ^1.1.2
  nostr_bunker: ^1.3.1
  nostr_widgets: ^1.1.0
  path: ^1.9.1
  path_provider: ^2.1.5
  sembast: ^3.8.5+1
  sembast_web: ^2.4.2
  toastification: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
